### ISSUE TITLE
v0.6.0 - KV TTL is not yet supported on Deno Deploy

### ISSUE THREAD

**Issue by ynwd** [denoland/deno_kv_oauth#177]
```
TypeError: KV TTL is not yet supported on Deno Deploy
    at Kv.denoNs.Kv.set (ext:deno_deploy/main.js:350:17)
    at setTokens (https://deno.land/x/deno_kv_oauth@v0.6.0/src/core.ts:178:12)
    at handleCallback (https://deno.land/x/deno_kv_oauth@v0.6.0/src/handle_callback.ts:67:9)
```

**Comment by iuioiua** [comment]
Thanks for raising an issue! I'll cut a release that implements the fix, shortly.
